name: Ultimate Android Build

on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  build-apk:
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Free up space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        df -h
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          openjdk-11-jdk \
          build-essential \
          git \
          unzip \
          python3-pip \
          python3-dev \
          python3-setuptools \
          python3-venv \
          zip \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev \
          autoconf \
          libtool \
          pkg-config
          
    - name: Setup Java environment
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
        echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV
        echo "/usr/lib/jvm/java-11-openjdk-amd64/bin" >> $GITHUB_PATH
        java -version
        
    - name: Upgrade pip and install Python dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install buildozer
        python3 -m pip install kivy
        python3 -m pip install cython
        
    - name: Verify installation
      run: |
        python3 --version
        pip --version
        buildozer --version
        echo "Java Home: $JAVA_HOME"
        
    - name: Clean previous builds
      run: |
        rm -rf .buildozer
        rm -rf bin
        
    - name: Create buildozer.spec if missing
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
        
    - name: Build APK
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
        export PATH=$JAVA_HOME/bin:$PATH
        buildozer android debug
        
    - name: List build results
      run: |
        echo "=== Build Results ==="
        ls -la
        if [ -d "bin" ]; then
          echo "=== APK Files ==="
          ls -la bin/
        else
          echo "No bin directory found"
        fi
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: calculator-apk
        path: bin/*.apk
        retention-days: 30
        
    - name: Upload logs on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-logs
        path: |
          .buildozer/logs/
          buildozer.log
        retention-days: 7
