name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 90

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache buildozer global directory
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Install system dependencies
      run: |
        sudo apt-get update -qq > /dev/null
        sudo apt-get install -qq --yes --no-install-recommends \
          build-essential git unzip openjdk-8-jdk python3-pip \
          python3-dev python3-setuptools python3-wheel python3-venv \
          zip zlib1g-dev libncurses5-dev libncursesw5-dev \
          libtinfo5 cmake libffi-dev libssl-dev autoconf \
          libtool ccache pkg-config > /dev/null

    - name: Install pip and buildozer
      run: |
        python -m pip install --upgrade pip
        python -m pip install buildozer==1.4.0
        python -m pip install kivy==2.1.0
        python -m pip install cython==0.29.32

    - name: Setup Java 8
      run: |
        echo "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $GITHUB_ENV
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

    - name: Verify buildozer installation
      run: |
        buildozer --version
        python --version
        java -version

    - name: Initialize buildozer
      run: |
        buildozer init || echo "buildozer.spec already exists"

    - name: Build Android APK
      run: |
        yes | buildozer android debug || buildozer android debug

    - name: Verify APK exists
      run: |
        ls -la bin/
        if [ ! -f bin/*.apk ]; then
          echo "❌ APK file not found!"
          exit 1
        fi
        echo "✅ APK built successfully!"

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: bin/*.apk

    - name: Show APK info
      run: |
        echo "APK Details:"
        ls -lah bin/*.apk
        echo "APK location: bin/"
        echo "Download from Actions > Artifacts section"
